services:
  transaction-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: transaction-app-container
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-container:3306/transaction_schema?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0.33
    container_name: mysql-container
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: transaction_schema
      MYSQL_USER: your_user
      MYSQL_PASSWORD: your_user

    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
